### ISSUE TITLE
Prepare node module structure

### ISSUE THREAD

**Issue by Alkon23** [oxpassword/oxpassword-core#2]
https://docs.npmjs.com/creating-node-js-modules

https://www.moonshot.partners/blog/creating-our-first-node-js-package-with-typescript#:~:text=package%20with%20TypeScript%3F-,The%20process%20of%20creating%20a%20Node.,to%20JavaScript%2C%20configuring%20the%20package.

https://medium.com/@plee_/7-simple-steps-to-build-your-own-typescript-node-js-project-5aea8320a05e

**Comment by molidev** [comment]
Example of node module structure:

node_module
│
├── src/                    
│   ├── index.js          # Main
│   └── utils.js            # Other functions
│
├── tests/                  # Unit test
│   └── index.test.js       
│
├── node_modules/           # Dependencies
│
├── .gitignore              
├── package.json           
└── README.md
